name = "cyrus-proxy"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV namespaces
[[kv_namespaces]]
binding = "OAUTH_TOKENS"
id = "0059e42e77684cceae31270ae414bc69"
preview_id = "oauth_tokens_preview"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "95059cf51611451798c3c01d5fe6b37c"
preview_id = "oauth_state_preview"

[[kv_namespaces]]
binding = "EDGE_TOKENS"
id = "a5ae263f67b9467fb87f0ffc5a1dc2c2"
preview_id = "edge_tokens_preview"

[[kv_namespaces]]
binding = "WORKSPACE_METADATA"
id = "d3dbfc5a847743fda38cfca37eee6dd5"
preview_id = "workspace_metadata_preview"

# Environment variables (use wrangler secret for production)
[vars]
OAUTH_REDIRECT_URI = "https://cyrus-proxy.holekun1.workers.dev/oauth/callback"



# Local development settings
[miniflare]
kv_persist = true